services:
  astro-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: santa-marta-turismo-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge